// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package port

import (
	"context"
	"reflect"

	"errors"
	"github.com/port-labs/pulumi-port/sdk/v2/go/port/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type BlueprintRelation struct {
	pulumi.CustomResourceState

	// The identifier of the blueprint the relation belongs to
	Blueprint pulumi.StringOutput `pulumi:"blueprint"`
	// The description of the relation. Port does not accept an empty value for this field, so removing it from the
	// configuration leaves the existing description in place rather than clearing it.
	Description pulumi.StringOutput `pulumi:"description"`
	// The identifier of the relation
	Identifier pulumi.StringOutput `pulumi:"identifier"`
	// Whether the relation points at many entities
	Many pulumi.BoolOutput `pulumi:"many"`
	// Whether the relation is required. Port rejects a required relation whose target blueprint already has a required
	// relation back to this one, so at most one direction of a circular pair can be required.
	Required pulumi.BoolOutput `pulumi:"required"`
	// The identifier of the blueprint the relation points at
	Target pulumi.StringOutput `pulumi:"target"`
	// The title of the relation. Port does not accept an empty value for this field, so removing it from the configuration
	// leaves the existing title in place rather than clearing it.
	Title pulumi.StringOutput `pulumi:"title"`
}

// NewBlueprintRelation registers a new resource with the given unique name, arguments, and options.
func NewBlueprintRelation(ctx *pulumi.Context,
	name string, args *BlueprintRelationArgs, opts ...pulumi.ResourceOption) (*BlueprintRelation, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Blueprint == nil {
		return nil, errors.New("invalid value for required argument 'Blueprint'")
	}
	if args.Identifier == nil {
		return nil, errors.New("invalid value for required argument 'Identifier'")
	}
	if args.Target == nil {
		return nil, errors.New("invalid value for required argument 'Target'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource BlueprintRelation
	err := ctx.RegisterResource("port:index/blueprintRelation:BlueprintRelation", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetBlueprintRelation gets an existing BlueprintRelation resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetBlueprintRelation(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *BlueprintRelationState, opts ...pulumi.ResourceOption) (*BlueprintRelation, error) {
	var resource BlueprintRelation
	err := ctx.ReadResource("port:index/blueprintRelation:BlueprintRelation", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering BlueprintRelation resources.
type blueprintRelationState struct {
	// The identifier of the blueprint the relation belongs to
	Blueprint *string `pulumi:"blueprint"`
	// The description of the relation. Port does not accept an empty value for this field, so removing it from the
	// configuration leaves the existing description in place rather than clearing it.
	Description *string `pulumi:"description"`
	// The identifier of the relation
	Identifier *string `pulumi:"identifier"`
	// Whether the relation points at many entities
	Many *bool `pulumi:"many"`
	// Whether the relation is required. Port rejects a required relation whose target blueprint already has a required
	// relation back to this one, so at most one direction of a circular pair can be required.
	Required *bool `pulumi:"required"`
	// The identifier of the blueprint the relation points at
	Target *string `pulumi:"target"`
	// The title of the relation. Port does not accept an empty value for this field, so removing it from the configuration
	// leaves the existing title in place rather than clearing it.
	Title *string `pulumi:"title"`
}

type BlueprintRelationState struct {
	// The identifier of the blueprint the relation belongs to
	Blueprint pulumi.StringPtrInput
	// The description of the relation. Port does not accept an empty value for this field, so removing it from the
	// configuration leaves the existing description in place rather than clearing it.
	Description pulumi.StringPtrInput
	// The identifier of the relation
	Identifier pulumi.StringPtrInput
	// Whether the relation points at many entities
	Many pulumi.BoolPtrInput
	// Whether the relation is required. Port rejects a required relation whose target blueprint already has a required
	// relation back to this one, so at most one direction of a circular pair can be required.
	Required pulumi.BoolPtrInput
	// The identifier of the blueprint the relation points at
	Target pulumi.StringPtrInput
	// The title of the relation. Port does not accept an empty value for this field, so removing it from the configuration
	// leaves the existing title in place rather than clearing it.
	Title pulumi.StringPtrInput
}

func (BlueprintRelationState) ElementType() reflect.Type {
	return reflect.TypeOf((*blueprintRelationState)(nil)).Elem()
}

type blueprintRelationArgs struct {
	// The identifier of the blueprint the relation belongs to
	Blueprint string `pulumi:"blueprint"`
	// The description of the relation. Port does not accept an empty value for this field, so removing it from the
	// configuration leaves the existing description in place rather than clearing it.
	Description *string `pulumi:"description"`
	// The identifier of the relation
	Identifier string `pulumi:"identifier"`
	// Whether the relation points at many entities
	Many *bool `pulumi:"many"`
	// Whether the relation is required. Port rejects a required relation whose target blueprint already has a required
	// relation back to this one, so at most one direction of a circular pair can be required.
	Required *bool `pulumi:"required"`
	// The identifier of the blueprint the relation points at
	Target string `pulumi:"target"`
	// The title of the relation. Port does not accept an empty value for this field, so removing it from the configuration
	// leaves the existing title in place rather than clearing it.
	Title *string `pulumi:"title"`
}

// The set of arguments for constructing a BlueprintRelation resource.
type BlueprintRelationArgs struct {
	// The identifier of the blueprint the relation belongs to
	Blueprint pulumi.StringInput
	// The description of the relation. Port does not accept an empty value for this field, so removing it from the
	// configuration leaves the existing description in place rather than clearing it.
	Description pulumi.StringPtrInput
	// The identifier of the relation
	Identifier pulumi.StringInput
	// Whether the relation points at many entities
	Many pulumi.BoolPtrInput
	// Whether the relation is required. Port rejects a required relation whose target blueprint already has a required
	// relation back to this one, so at most one direction of a circular pair can be required.
	Required pulumi.BoolPtrInput
	// The identifier of the blueprint the relation points at
	Target pulumi.StringInput
	// The title of the relation. Port does not accept an empty value for this field, so removing it from the configuration
	// leaves the existing title in place rather than clearing it.
	Title pulumi.StringPtrInput
}

func (BlueprintRelationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*blueprintRelationArgs)(nil)).Elem()
}

type BlueprintRelationInput interface {
	pulumi.Input

	ToBlueprintRelationOutput() BlueprintRelationOutput
	ToBlueprintRelationOutputWithContext(ctx context.Context) BlueprintRelationOutput
}

func (*BlueprintRelation) ElementType() reflect.Type {
	return reflect.TypeOf((**BlueprintRelation)(nil)).Elem()
}

func (i *BlueprintRelation) ToBlueprintRelationOutput() BlueprintRelationOutput {
	return i.ToBlueprintRelationOutputWithContext(context.Background())
}

func (i *BlueprintRelation) ToBlueprintRelationOutputWithContext(ctx context.Context) BlueprintRelationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BlueprintRelationOutput)
}

// BlueprintRelationArrayInput is an input type that accepts BlueprintRelationArray and BlueprintRelationArrayOutput values.
// You can construct a concrete instance of `BlueprintRelationArrayInput` via:
//
//	BlueprintRelationArray{ BlueprintRelationArgs{...} }
type BlueprintRelationArrayInput interface {
	pulumi.Input

	ToBlueprintRelationArrayOutput() BlueprintRelationArrayOutput
	ToBlueprintRelationArrayOutputWithContext(context.Context) BlueprintRelationArrayOutput
}

type BlueprintRelationArray []BlueprintRelationInput

func (BlueprintRelationArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*BlueprintRelation)(nil)).Elem()
}

func (i BlueprintRelationArray) ToBlueprintRelationArrayOutput() BlueprintRelationArrayOutput {
	return i.ToBlueprintRelationArrayOutputWithContext(context.Background())
}

func (i BlueprintRelationArray) ToBlueprintRelationArrayOutputWithContext(ctx context.Context) BlueprintRelationArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BlueprintRelationArrayOutput)
}

// BlueprintRelationMapInput is an input type that accepts BlueprintRelationMap and BlueprintRelationMapOutput values.
// You can construct a concrete instance of `BlueprintRelationMapInput` via:
//
//	BlueprintRelationMap{ "key": BlueprintRelationArgs{...} }
type BlueprintRelationMapInput interface {
	pulumi.Input

	ToBlueprintRelationMapOutput() BlueprintRelationMapOutput
	ToBlueprintRelationMapOutputWithContext(context.Context) BlueprintRelationMapOutput
}

type BlueprintRelationMap map[string]BlueprintRelationInput

func (BlueprintRelationMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*BlueprintRelation)(nil)).Elem()
}

func (i BlueprintRelationMap) ToBlueprintRelationMapOutput() BlueprintRelationMapOutput {
	return i.ToBlueprintRelationMapOutputWithContext(context.Background())
}

func (i BlueprintRelationMap) ToBlueprintRelationMapOutputWithContext(ctx context.Context) BlueprintRelationMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BlueprintRelationMapOutput)
}

type BlueprintRelationOutput struct{ *pulumi.OutputState }

func (BlueprintRelationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**BlueprintRelation)(nil)).Elem()
}

func (o BlueprintRelationOutput) ToBlueprintRelationOutput() BlueprintRelationOutput {
	return o
}

func (o BlueprintRelationOutput) ToBlueprintRelationOutputWithContext(ctx context.Context) BlueprintRelationOutput {
	return o
}

// The identifier of the blueprint the relation belongs to
func (o BlueprintRelationOutput) Blueprint() pulumi.StringOutput {
	return o.ApplyT(func(v *BlueprintRelation) pulumi.StringOutput { return v.Blueprint }).(pulumi.StringOutput)
}

// The description of the relation. Port does not accept an empty value for this field, so removing it from the
// configuration leaves the existing description in place rather than clearing it.
func (o BlueprintRelationOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *BlueprintRelation) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// The identifier of the relation
func (o BlueprintRelationOutput) Identifier() pulumi.StringOutput {
	return o.ApplyT(func(v *BlueprintRelation) pulumi.StringOutput { return v.Identifier }).(pulumi.StringOutput)
}

// Whether the relation points at many entities
func (o BlueprintRelationOutput) Many() pulumi.BoolOutput {
	return o.ApplyT(func(v *BlueprintRelation) pulumi.BoolOutput { return v.Many }).(pulumi.BoolOutput)
}

// Whether the relation is required. Port rejects a required relation whose target blueprint already has a required
// relation back to this one, so at most one direction of a circular pair can be required.
func (o BlueprintRelationOutput) Required() pulumi.BoolOutput {
	return o.ApplyT(func(v *BlueprintRelation) pulumi.BoolOutput { return v.Required }).(pulumi.BoolOutput)
}

// The identifier of the blueprint the relation points at
func (o BlueprintRelationOutput) Target() pulumi.StringOutput {
	return o.ApplyT(func(v *BlueprintRelation) pulumi.StringOutput { return v.Target }).(pulumi.StringOutput)
}

// The title of the relation. Port does not accept an empty value for this field, so removing it from the configuration
// leaves the existing title in place rather than clearing it.
func (o BlueprintRelationOutput) Title() pulumi.StringOutput {
	return o.ApplyT(func(v *BlueprintRelation) pulumi.StringOutput { return v.Title }).(pulumi.StringOutput)
}

type BlueprintRelationArrayOutput struct{ *pulumi.OutputState }

func (BlueprintRelationArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*BlueprintRelation)(nil)).Elem()
}

func (o BlueprintRelationArrayOutput) ToBlueprintRelationArrayOutput() BlueprintRelationArrayOutput {
	return o
}

func (o BlueprintRelationArrayOutput) ToBlueprintRelationArrayOutputWithContext(ctx context.Context) BlueprintRelationArrayOutput {
	return o
}

func (o BlueprintRelationArrayOutput) Index(i pulumi.IntInput) BlueprintRelationOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *BlueprintRelation {
		return vs[0].([]*BlueprintRelation)[vs[1].(int)]
	}).(BlueprintRelationOutput)
}

type BlueprintRelationMapOutput struct{ *pulumi.OutputState }

func (BlueprintRelationMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*BlueprintRelation)(nil)).Elem()
}

func (o BlueprintRelationMapOutput) ToBlueprintRelationMapOutput() BlueprintRelationMapOutput {
	return o
}

func (o BlueprintRelationMapOutput) ToBlueprintRelationMapOutputWithContext(ctx context.Context) BlueprintRelationMapOutput {
	return o
}

func (o BlueprintRelationMapOutput) MapIndex(k pulumi.StringInput) BlueprintRelationOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *BlueprintRelation {
		return vs[0].(map[string]*BlueprintRelation)[vs[1].(string)]
	}).(BlueprintRelationOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*BlueprintRelationInput)(nil)).Elem(), &BlueprintRelation{})
	pulumi.RegisterInputType(reflect.TypeOf((*BlueprintRelationArrayInput)(nil)).Elem(), BlueprintRelationArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*BlueprintRelationMapInput)(nil)).Elem(), BlueprintRelationMap{})
	pulumi.RegisterOutputType(BlueprintRelationOutput{})
	pulumi.RegisterOutputType(BlueprintRelationArrayOutput{})
	pulumi.RegisterOutputType(BlueprintRelationMapOutput{})
}
