// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("port");

export declare const baseUrl: string | undefined;
Object.defineProperty(exports, "baseUrl", {
    get() {
        return __config.get("baseUrl");
    },
    enumerable: true,
});

/**
 * Protects you from accidentally changing the property type of blueprints which will delete the property before recreating
 * it with the new type. Defaults to `true`
 */
export declare const blueprintPropertyTypeChangeProtection: boolean | undefined;
Object.defineProperty(exports, "blueprintPropertyTypeChangeProtection", {
    get() {
        return __config.getObject<boolean>("blueprintPropertyTypeChangeProtection");
    },
    enumerable: true,
});

/**
 * Client ID for Port-labs
 */
export declare const clientId: string | undefined;
Object.defineProperty(exports, "clientId", {
    get() {
        return __config.get("clientId");
    },
    enumerable: true,
});

/**
 * When set to `false` disables the default HTML escaping of json.Marshal when reading data from Port. Defaults to `true`
 */
export declare const jsonEscapeHtml: boolean | undefined;
Object.defineProperty(exports, "jsonEscapeHtml", {
    get() {
        return __config.getObject<boolean>("jsonEscapeHtml");
    },
    enumerable: true,
});

/**
 * Client Secret for Port-labs
 */
export declare const secret: string | undefined;
Object.defineProperty(exports, "secret", {
    get() {
        return __config.get("secret");
    },
    enumerable: true,
});

/**
 * Token for Port-labs
 */
export declare const token: string | undefined;
Object.defineProperty(exports, "token", {
    get() {
        return __config.get("token");
    },
    enumerable: true,
});

