env:
  GH_TOKEN: ${{ secrets.MACHINE_USER_TOKEN }}
jobs:
  upgrade_provider:
    name: upgrade-provider
    runs-on: ubuntu-latest
    steps:
    - name: Call upgrade provider action
      uses: pulumi/pulumi-upgrade-provider-action@ff5cb5907aecba099e61146c4d4d074c7fd6ca99 # v0.0.15
      with:
        kind: provider
        email: getport.io
        username: pulumi-port-bot
name: Upgrade the TF provider only

permissions:
  contents: write

on:
  workflow_dispatch: {}
