env:
  GH_TOKEN: ${{ secrets.MACHINE_USER_TOKEN }}
jobs:
  upgrade_provider:
    name: upgrade-provider
    runs-on: ubuntu-latest
    steps:
    - name: Call upgrade provider action
      uses: pulumi/pulumi-upgrade-provider-action@f399a75a5350242c291cc720eece1c72cb6ea712 # v0.0.12
      with:
        kind: provider
        email: getport.io
        username: pulumi-port-bot
        go-version: '1.24'
name: Upgrade the TF provider only

permissions:
  contents: write

on:
  workflow_dispatch: {}
