// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Integration extends pulumi.CustomResource {
    /**
     * Get an existing Integration resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IntegrationState, opts?: pulumi.CustomResourceOptions): Integration {
        return new Integration(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'port:index/integration:Integration';

    /**
     * Returns true if the given object is an instance of Integration.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Integration {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Integration.__pulumiType;
    }

    public readonly config!: pulumi.Output<string>;
    /**
     * Controls whether Port creates default blueprints and mappings when the integration is created. Use `Empty` to skip
     * default resource creation. Use `Port` to create default resources via Port. If omitted, default resources are created.
     * Can only be set on creation.
     */
    public readonly createPortResourcesOrigin!: pulumi.Output<string | undefined>;
    /**
     * The integrated tool name for catalog integration types (e.g. `github-ocean`, `gitlab`, `pagerduty`). Cannot be changed
     * after creation.
     */
    public readonly installationAppType!: pulumi.Output<string | undefined>;
    /**
     * The installation ID of the integration. Must contain only lowercase letters, numbers, and dashes (pattern:
     * `^[a-z0-9-]+$`). Cannot be changed after creation.
     */
    public readonly installationId!: pulumi.Output<string>;
    /**
     * The installation type of the integration. Use `Saas` for Port Hosted integrations (requires `spec`). Defaults to
     * `OnPrem` for self-hosted integrations. Only `OnPrem` and `Saas` are supported by this resource. Cannot be changed after
     * creation.
     */
    public readonly installationType!: pulumi.Output<string>;
    /**
     * The changelog destination of the blueprint (just an empty `{}`)
     */
    public readonly kafkaChangelogDestination!: pulumi.Output<outputs.IntegrationKafkaChangelogDestination>;
    /**
     * Port Hosted integration spec as a JSON string (use `jsonencode`). **Only supported when `installationType` is `Saas`**
     * — must not be set for self-hosted integrations. Required for Port Hosted integrations. Contains `integrationSpec`
     * (credentials/settings) and optionally `appSpec` (feature toggles like `liveEventsEnabled`, `sendRawDataExamples`, etc.).
     * Sensitive `integrationSpec` values (org secret references) are preserved from your HCL on read. If `appSpec` fields are
     * omitted, Port applies its own defaults — which may differ from Port UI defaults. Declare `appSpec` explicitly to match
     * the UI behavior.
     */
    public readonly spec!: pulumi.Output<string>;
    /**
     * The provisioning status of the integration (e.g. `Creating`, `Running`, `Updating`, `Error`). Relevant for Port Hosted
     * integrations that provision asynchronously.
     */
    public /*out*/ readonly status!: pulumi.Output<string>;
    public readonly title!: pulumi.Output<string | undefined>;
    public readonly version!: pulumi.Output<string>;
    /**
     * The webhook changelog destination of the integration
     */
    public readonly webhookChangelogDestination!: pulumi.Output<outputs.IntegrationWebhookChangelogDestination>;

    /**
     * Create a Integration resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IntegrationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IntegrationArgs | IntegrationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IntegrationState | undefined;
            resourceInputs["config"] = state ? state.config : undefined;
            resourceInputs["createPortResourcesOrigin"] = state ? state.createPortResourcesOrigin : undefined;
            resourceInputs["installationAppType"] = state ? state.installationAppType : undefined;
            resourceInputs["installationId"] = state ? state.installationId : undefined;
            resourceInputs["installationType"] = state ? state.installationType : undefined;
            resourceInputs["kafkaChangelogDestination"] = state ? state.kafkaChangelogDestination : undefined;
            resourceInputs["spec"] = state ? state.spec : undefined;
            resourceInputs["status"] = state ? state.status : undefined;
            resourceInputs["title"] = state ? state.title : undefined;
            resourceInputs["version"] = state ? state.version : undefined;
            resourceInputs["webhookChangelogDestination"] = state ? state.webhookChangelogDestination : undefined;
        } else {
            const args = argsOrState as IntegrationArgs | undefined;
            if ((!args || args.installationId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'installationId'");
            }
            resourceInputs["config"] = args ? args.config : undefined;
            resourceInputs["createPortResourcesOrigin"] = args ? args.createPortResourcesOrigin : undefined;
            resourceInputs["installationAppType"] = args ? args.installationAppType : undefined;
            resourceInputs["installationId"] = args ? args.installationId : undefined;
            resourceInputs["installationType"] = args ? args.installationType : undefined;
            resourceInputs["kafkaChangelogDestination"] = args ? args.kafkaChangelogDestination : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["title"] = args ? args.title : undefined;
            resourceInputs["version"] = args ? args.version : undefined;
            resourceInputs["webhookChangelogDestination"] = args ? args.webhookChangelogDestination : undefined;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Integration.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Integration resources.
 */
export interface IntegrationState {
    config?: pulumi.Input<string>;
    /**
     * Controls whether Port creates default blueprints and mappings when the integration is created. Use `Empty` to skip
     * default resource creation. Use `Port` to create default resources via Port. If omitted, default resources are created.
     * Can only be set on creation.
     */
    createPortResourcesOrigin?: pulumi.Input<string>;
    /**
     * The integrated tool name for catalog integration types (e.g. `github-ocean`, `gitlab`, `pagerduty`). Cannot be changed
     * after creation.
     */
    installationAppType?: pulumi.Input<string>;
    /**
     * The installation ID of the integration. Must contain only lowercase letters, numbers, and dashes (pattern:
     * `^[a-z0-9-]+$`). Cannot be changed after creation.
     */
    installationId?: pulumi.Input<string>;
    /**
     * The installation type of the integration. Use `Saas` for Port Hosted integrations (requires `spec`). Defaults to
     * `OnPrem` for self-hosted integrations. Only `OnPrem` and `Saas` are supported by this resource. Cannot be changed after
     * creation.
     */
    installationType?: pulumi.Input<string>;
    /**
     * The changelog destination of the blueprint (just an empty `{}`)
     */
    kafkaChangelogDestination?: pulumi.Input<inputs.IntegrationKafkaChangelogDestination>;
    /**
     * Port Hosted integration spec as a JSON string (use `jsonencode`). **Only supported when `installationType` is `Saas`**
     * — must not be set for self-hosted integrations. Required for Port Hosted integrations. Contains `integrationSpec`
     * (credentials/settings) and optionally `appSpec` (feature toggles like `liveEventsEnabled`, `sendRawDataExamples`, etc.).
     * Sensitive `integrationSpec` values (org secret references) are preserved from your HCL on read. If `appSpec` fields are
     * omitted, Port applies its own defaults — which may differ from Port UI defaults. Declare `appSpec` explicitly to match
     * the UI behavior.
     */
    spec?: pulumi.Input<string>;
    /**
     * The provisioning status of the integration (e.g. `Creating`, `Running`, `Updating`, `Error`). Relevant for Port Hosted
     * integrations that provision asynchronously.
     */
    status?: pulumi.Input<string>;
    title?: pulumi.Input<string>;
    version?: pulumi.Input<string>;
    /**
     * The webhook changelog destination of the integration
     */
    webhookChangelogDestination?: pulumi.Input<inputs.IntegrationWebhookChangelogDestination>;
}

/**
 * The set of arguments for constructing a Integration resource.
 */
export interface IntegrationArgs {
    config?: pulumi.Input<string>;
    /**
     * Controls whether Port creates default blueprints and mappings when the integration is created. Use `Empty` to skip
     * default resource creation. Use `Port` to create default resources via Port. If omitted, default resources are created.
     * Can only be set on creation.
     */
    createPortResourcesOrigin?: pulumi.Input<string>;
    /**
     * The integrated tool name for catalog integration types (e.g. `github-ocean`, `gitlab`, `pagerduty`). Cannot be changed
     * after creation.
     */
    installationAppType?: pulumi.Input<string>;
    /**
     * The installation ID of the integration. Must contain only lowercase letters, numbers, and dashes (pattern:
     * `^[a-z0-9-]+$`). Cannot be changed after creation.
     */
    installationId: pulumi.Input<string>;
    /**
     * The installation type of the integration. Use `Saas` for Port Hosted integrations (requires `spec`). Defaults to
     * `OnPrem` for self-hosted integrations. Only `OnPrem` and `Saas` are supported by this resource. Cannot be changed after
     * creation.
     */
    installationType?: pulumi.Input<string>;
    /**
     * The changelog destination of the blueprint (just an empty `{}`)
     */
    kafkaChangelogDestination?: pulumi.Input<inputs.IntegrationKafkaChangelogDestination>;
    /**
     * Port Hosted integration spec as a JSON string (use `jsonencode`). **Only supported when `installationType` is `Saas`**
     * — must not be set for self-hosted integrations. Required for Port Hosted integrations. Contains `integrationSpec`
     * (credentials/settings) and optionally `appSpec` (feature toggles like `liveEventsEnabled`, `sendRawDataExamples`, etc.).
     * Sensitive `integrationSpec` values (org secret references) are preserved from your HCL on read. If `appSpec` fields are
     * omitted, Port applies its own defaults — which may differ from Port UI defaults. Declare `appSpec` explicitly to match
     * the UI behavior.
     */
    spec?: pulumi.Input<string>;
    title?: pulumi.Input<string>;
    version?: pulumi.Input<string>;
    /**
     * The webhook changelog destination of the integration
     */
    webhookChangelogDestination?: pulumi.Input<inputs.IntegrationWebhookChangelogDestination>;
}
